name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  contacts_service: ^0.6.3
  country_picker: ^2.0.26
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  story_view: ^0.16.5
  uuid: ^4.5.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  country_code_picker: ^3.0.0
  circle_flags: ^5.0.0
  url_launcher: ^6.3.0
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gift/
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/icons/chat.png
    - assets/images/balance.avif
    - assets/images/balance.jpeg
    - assets/placeholder.png
    - assets/avatar.jpg
    - assets/images/coverpic.png
    - assets/images/room.png
    - assets/images/robot.jpg
    - assets/icons/ic-user.svg
    - assets/images/avatar.png
    - assets/images/gift.png
    - assets/backAvatar.jpg
    - assets/gifts/gift1.png
    - assets/gifts/gift2.png
    - assets/gifts/gift3.png
    - assets/gifts/gift4.png
    - assets/gifts/gift5.png
    - assets/gifts/gift6.png
    - assets/gifts/gift7.png
    - assets/gifts/gift8.png
    - assets/gifts/gift9.png
    - assets/icons/chat.png
    - assets/images/balance.avif
    - assets/images/balance.jpeg
    - assets/placeholder.png
    - assets/Resizers/
    - assets/
    - assets/banners/1.png
    - assets/banners/2.png
    - assets/banners/3.png
